hydra_base_dir : " "
seed : 0
unif_init : False
n_agent : 10
exp2 : False
distribution: "Bernoulli"
network:
  nodes_nbr: 3
  edges:
    "0": [1,2] # Convention "EdgeNumber": [Parent Node, Child Node]
    "1": [0,1]
    "2": [0,1]
    "3": [0,1]
    "4": [0,1]
    "5": [0,1]
    "6": [0,1]
    "7": [0,1]
    "8": [0,1]
    "9": [0,1]
    "10": [0,1]
    "11": [0,1]
    "12": [0,1]
    "13": [1,2]
    "14": [1,2]
    "15": [1,2] 
    "16": [1,2]
    "17": [1,2]
    "18": [1,2]  
    "19": [1,2]
    "20": [1,2]
    "21": [1,2] 
    "22": [1,2]
    "23": [1,2]
    "24": [1,2]   
