hydra_base_dir : " "
seed : 0
unif_init : True
n_agent : 5
exp2 : False
distribution: "Bernoulli"
compute_exploitability: False
include_others: True
network:
  nodes_nbr: 20
  edges:
    "0": [0,1] # Convention "EdgeNumber": [Parent Node, Child Node]
    "1": [0,1]
    "2": [1,2]
    "3": [1,2]
    "4": [2,3]
    "5": [2,3]
    "6": [3,4]
    "7": [3,4]
    "8": [4,5]
    "9": [4,5]
    "10": [5,6]
    "11": [5,6]
    "12": [6,7]
    "13": [6,7]
    "14": [7,8]
    "15": [7,8] 
    "16": [8,9]
    "17": [8,9]
    "18": [9,10]  
    "19": [9,10]
    "20": [10,11]
    "21": [10,11] 
    "22": [11,12]
    "23": [11,12]
    "24": [12,13]  
    "25": [12,13] 
    "26": [13,14]
    "27": [13,14]
    "28": [14,15]
    "29": [14,15] 
    "30": [15,16]
    "31": [15,16]
    "32": [16,17]  
    "33": [16,17] 
    "34": [17,18]
    "35": [17,18]
    "36": [18,19]  
    "37": [18,19]

